#!/bin/sh
# This board's "WAN" (eth1) actually sits on the trusted home network behind
# the ONT (192.168.2.0/24), not the public internet -- alcove and other
# trusted hosts live there too. Allow SSH and the LuCI web UI (http/https)
# from that zone so the board is reachable without needing the direct LAN
# cable.
#
# NOTE: this is safe only because eth1 is NOT actually internet-facing on
# this experimental topology. Do not carry these rules into a real
# WAN-facing deployment.
uci add firewall rule
uci set firewall.@rule[-1].name='Allow-SSH-WAN'
uci set firewall.@rule[-1].src='wan'
uci set firewall.@rule[-1].proto='tcp'
uci set firewall.@rule[-1].dest_port='22'
uci set firewall.@rule[-1].target='ACCEPT'

uci add firewall rule
uci set firewall.@rule[-1].name='Allow-HTTP-WAN'
uci set firewall.@rule[-1].src='wan'
uci set firewall.@rule[-1].proto='tcp'
uci set firewall.@rule[-1].dest_port='80'
uci set firewall.@rule[-1].target='ACCEPT'

uci add firewall rule
uci set firewall.@rule[-1].name='Allow-HTTPS-WAN'
uci set firewall.@rule[-1].src='wan'
uci set firewall.@rule[-1].proto='tcp'
uci set firewall.@rule[-1].dest_port='443'
uci set firewall.@rule[-1].target='ACCEPT'

uci commit firewall

exit 0
